### ISSUE TITLE
Response always incomplete.

### ISSUE THREAD

**Issue by ydche3** [rksm/org-ai#10]
When I ask AI on English, the responses always complete. But when it comes to Chinese, the responses always incomplete. I have to ask AI to go on several times that I can get the whole content of response. How could I ask AI to show the whole content?

**Comment by alan-w-255** [comment]
Try to increase the max-tokens to 2000.

**Comment by rksm** [comment]
Yeah that should help. In the latest version the [default max tokens](https://github.com/rksm/org-ai/blob/master/org-ai.el#L75) is set to nil (it was 120) and so uses the OpenAI defaults. 120 was too low to deliver useful responses for most prompts.

**Comment by ydche3** [comment]
> Try to increase the max-tokens to 2000.

Think. It works.

**Comment by ydche3** [comment]
> Yeah that should help. In the latest version the [default max tokens](https://github.com/rksm/org-ai/blob/master/org-ai.el#L75) is set to nil (it was 120) and so uses the OpenAI defaults. 120 was too low to deliver useful responses for most prompts.

It works. Thinks.
