### ISSUE TITLE
possible to access dall-e-3?

### ISSUE THREAD

**Issue by titaniumbones** [rksm/org-ai#101]
I'd like to use dall-e-3 when generating images.  I tried adding a "model" parameter to org-ai--image-request, but that seems to break the image save, and I can't understnad why, despite some experimenting with CURL.  Do you have any thoughts?

**Comment by rksm** [comment]
DALL·E-3 should now be the default model to use. The `:model` keyword in image blocks should now also work (alternatively setting `org-ai-image-model` to `"dall-e-2"` if the older model is preferred).

**Comment by titaniumbones** [comment]
wow, that was so quick and it now works perfectly.  Thank you.  

note: :n must be set to 1 or the request fails; not sure if it's possible to get an error message sent to `*Messages*`; I have always had a tough time getting `request` to provide those for me in a transparent way. 

thanks so much!

**Comment by rksm** [comment]
> n must be set to 1 or the request fails

Hmm this is strange, can't reproduce this with a fresh install. It could be that the `org-ai-image-default-count` didn't get initialized correctly for you for some reason. You can customize it with `M-x customize-variable` or set it in your config with `(setq org-ai-image-default-count 1)`
