### ISSUE TITLE
auto-fill-mode in the answer?

### ISSUE THREAD

**Issue by grauschnabel** [rksm/org-ai#109]
Hi!

I like your package very much. But I wonder if there is a way to make it use the auto-fill-mode when answering?  As now I need to go to each paragraph and wrap it manually.  Do you have an idea about that?

Thanks,
Martin

**Comment by rksm** [comment]
Should work now by setting `org-ai-auto-fill`: https://github.com/rksm/org-ai?tab=readme-ov-file#auto-fill-paragraphs-on-insertion
