### ISSUE TITLE
org-ai--openai-get-token broken

### ISSUE THREAD

**Issue by andreas-roehler** [rksm/org-ai#113]
@KaratasFurkan commented on this pull request.

In [org-ai-openai.el](https://github.com/rksm/org-ai/pull/112#discussion_r1629452822):

> -(defcustom org-ai-openai-api-token nil
+(defcustom org-ai-openai-api-token ""

Hi @andreas-roehler , @rksm , this change breaks the or condition here: https://github.com/andreas-roehler/org-ai/blob/f052119c9f622f1ddb698c08e1ce3bf60b39959f/org-ai-openai.el#L172

The reason is or returns the first non-nil value (e.g. (or nil "" "test") returns ""), which is the empty string in this case.

**Comment by andreas-roehler** [comment]
The empty string evaluates to boolean t in elisp, which seems a little bit odd, but that's how it is. Fix in preparation.

**Comment by rksm** [comment]
Thanks for reporting and fixing!

ref https://github.com/rksm/org-ai/pull/114
