### ISSUE TITLE
org-ai-on-project fails for Anthropic

### ISSUE THREAD

**Issue by dangirsh** [rksm/org-ai#118]
Thanks for the quick fix on #116 ! Claude Sonnet is a clear step up in programming capabilities. But, I seem to be the first one to try Anthropic with org-ai recently....

When running `org-ai-on-project`, I get:

> Error from the service API:
> 
> max_tokens: Field required

Switching to openai fixes it. Setting `org-ai-default-max-tokens` doesn't.

**Comment by dangirsh** [comment]
Once this works, Claude should take care of any future issues ;)

**Comment by rksm** [comment]
Hah someone is using `org-ai-on-project` very cool :+1:

**Comment by rksm** [comment]
It's been a while since I last tried the auto-patch feature, it seems much better now. Time to really give it a spin again.
