### ISSUE TITLE
Getting the entire chatgpt response when done

### ISSUE THREAD

**Issue by mrspeaker** [rksm/org-ai#12]
This is a feature request - and one that is probably way out of scope (so feel free to just close this issue)

I've been using org-ai a lot recently. More and more I'm not using it directly in an org buffer, but I have a function that prompts for input, then runs that in a new org buffer - like this (excuse my beginner elisp):

```lisp
(defun chat-gpt (prompt)
  (interactive
   (list
    (read-string "Sup? ")))
  (pop-to-buffer (get-buffer-create (generate-new-buffer-name "*org-ai*")))
  (insert "#+begin_ai\n")
  (insert prompt)
  (insert "\n#+end_ai")
  (org-mode)
  (previous-line)
  (org-ai-ctrl-c-ctrl-c))
```

I use this fifty times a day (thanks for org-ai, it's fantastic!). But now I want to take it further and use the output from a prompt directly in the code I write. My use case is that I'm doing a lot of running the above function, then when it's done, copy-pasting the result of the `[AI]:` section into my code as a variable and then using for further processing (Same with the generated images - I run the prompt then have to manually copy/paste the generated url and stick it in a defvar).

I'd really to be able to skip the manual copy/paste step: just run a prompt, and have the full result available in a variable. However, I started poking around your code and it looks tricky, given that the result is a stream. There is a "done" area in `org-ai--insert-chat-completion-response` but I can't figure out how I might extract the full AI response from that.

Anyhoo, feel free to close this issue: I was just wondering if you had any suggestions on how I could go about that, and also to suggest that there might be some value in exposing more of the internals as more of a generic API rather than just an org-mode output. Thanks again for the package, it rocks!

**Comment by rksm** [comment]
Thanks for the feedback and yeah the feature is super interesting, I thought about that as well.

I've recently been made aware of https://thakkarparth007.github.io/copilot-explorer/posts/copilot-internals which shows how some of the buffer context is exposed copilot/codex. This might be potentially quite interesting as the current buffer can already be used as context, the current point as `<INSERT HERE>` token etc.

To make your current life a little easier, here is a slightly extended version of your function that will just insert the result into a new buffer:

```elisp

(defun chat-gpt (prompt)
  "Prompt for an input, send it to chatgpt and insert the response
into a new buffer."
  (interactive
   (list
    (read-string "Sup? ")))
  (lexical-let ((output-buffer (get-buffer-create (generate-new-buffer-name "*org-ai*"))))
    (let ((input (format "[SYS]: Be nice, please.\n[ME]: %s" prompt)))
      (pop-to-buffer output-buffer)
      (org-ai-stream-request :messages (org-ai--collect-chat-messages input)
                             :model "gpt-3.5-turbo"
                             :max-tokens 100
                             :callback (lambda (response)
                                         (when-let* ((choices (or (alist-get 'choices response)
                                                                  (plist-get response 'choices)))
                                                     (choice (aref choices 0)))
                                           (let ((delta (plist-get choice 'delta)))
                                             (cond
                                              ((plist-get delta 'content)
                                               (let ((text (plist-get delta 'content)))
                                                 (with-current-buffer output-buffer
                                                   (insert (decode-coding-string text 'utf-8)))))
                                              ((plist-get choice 'finish_reason)
                                               (with-current-buffer output-buffer
                                                 (mark-whole-buffer)))))))))))
```

With this you could of course just use the current buffer as output and directly insert the response, e.g.

```elisp
(defun chat-gpt (prompt)
  "Prompt for an input, send it to chatgpt and insert the response
in the current buffer and select it."
  (interactive
   (list
    (read-string "Sup? ")))
  (lexical-let ((output-buffer (current-buffer))
                (start-pos (point)))
    (let ((input (format "[SYS]: Be nice, please.\n[ME]: %s" prompt)))
      (pop-to-buffer output-buffer)
      (org-ai-stream-request :messages (org-ai--collect-chat-messages input)
                             :model "gpt-3.5-turbo"
                             :max-tokens 100
                             :callback (lambda (response)
                                         (when-let* ((choices (or (alist-get 'choices response)
                                                                  (plist-get response 'choices)))
                                                     (choice (aref choices 0)))
                                           (let ((delta (plist-get choice 'delta)))
                                             (cond
                                              ((plist-get delta 'content)
                                               (let ((text (plist-get delta 'content)))
                                                 (with-current-buffer output-buffer
                                                   (insert (decode-coding-string text 'utf-8)))))
                                              ((plist-get choice 'finish_reason)
                                               (with-current-buffer output-buffer
                                                 (set-mark (point))
                                                 (goto-char start-pos)))))))))))
```

I'll add something like this into the package itself soon.

**Comment by mrspeaker** [comment]
Holy cow, that is perfect! Thanks so much, and thanks again for the package... I'm having a blast with it!
