### ISSUE TITLE
Setting up Anthropic

### ISSUE THREAD

**Issue by lambdaofgod** [rksm/org-ai#131]
I followed the steps from documentation, that is I added the line

```
machine api.anthropic.com login org-ai password sk-ant-***
```
Where I added my API key.

When I try to run org-ai block 
```
#+BEGIN_AI :service anthropic :model claude-3-opus-20240229
What is 2 + two?
#+END_AI
```

I get asked  `Username for [https:// api.anthropic.com/v1/messages]:`

Which doesn't seem like it was configured properly.

I use org-ai 20240806.1340

**Comment by rksm** [comment]
Could you try to evaluate `(auth-source-pick-first-password :host "api.anthropic.com" :user "org-ai")` and see if that works?

If all else fails you can also set `org-ai-openai-api-token` directly (it'll work for anthropic despite the name).

**Comment by jixiuf** [comment]
maybe you need add another linke with port  443

like `machine api.openai.com:443 login apikey password sk-*`

**Comment by lambdaofgod** [comment]
@rksm your approach basically works.

I made a helper for loading keys from files (I had problems with encrypted secrets and GPG), maybe someone will find this useful

```

(setq openai-api-key-path "<PATH>")
(setq anthropic-api-key-path "<PATH>")


(defvar org-ai-openai-api-token "")

(defun get-key-from-file (api-key-path)
  (with-temp-buffer
    (insert-file-contents api-key-path)
    (string-trim (buffer-string))))
  

(defun set-openai-key ()
    (interactive)
    (let ((openai-key-path (read-string "openai key path, default:" openai-api-key-path)))
        (progn
            (setq org-ai-openai-api-token (get-key-from-file openai-key-path))
            (message (concat "loaded org-openai-api-token"))
            (org-ai-switch-chat-model))))


(defun set-anthropic-key ()
    (interactive)
    (let ((anthropic-key-path (read-string "anthropic key path, default:" anthropic-api-key-path)))
        (progn
            (setq org-ai-anthropic-api-token (get-key-from-file anthropic-key-path))
            (message (concat "set anthropic api token"))
            (setq org-ai-openai-api-token org-ai-anthropic-api-token)
            (setq org-ai-service "anthropic")
            (org-ai-switch-chat-model))))
```
