### ISSUE TITLE
design question re special-blocks vs babel begin_src / end_src

### ISSUE THREAD

**Issue by tavisrudd** [rksm/org-ai#17]
Hi, I'm loving this library. Thanks for your work on it and especially the new non-org-mode features in 0.2.

I'm curious if you considered using babel src blocks instead of special-blocks? A disadvantage of special-blocks is the lack of syntax highlighting in them. In particular, I'd love to have the blocks fontified as markdown. I know how to configure that easily in custom src blocks but don't see how to do it in special-blocks.

**Comment by rksm** [comment]
Hi thank you and yeah, the syntax highlighting is an issue.

The reason for not reusing babel src blocks was that there is a whole lot of very specific behavior implemented around that, that didn't fit well with the chat idea.

[Special blocks](https://git.sr.ht/~bzg/org-mode/tree/1a6d5f11d/lisp/org-element.el#L1874) are sort of a first class concept in org-mode which generally is what we want. The syntax is defined by [org-element-special-block-interpreter](https://git.sr.ht/~bzg/org-mode/tree/1a6d5f11d/lisp/org-element.el#L1925)
and the highlighting (font-lock) gets assigned by [this function](https://git.sr.ht/~bzg/org-mode/tree/1a6d5f11d/lisp/org.el#L5363), in particular [this section](https://git.sr.ht/~bzg/org-mode/tree/1a6d5f11d/lisp/org.el#L5389).

There we can find out that there is such a thing as a `org-protecting-blocks` list which by default is `'("src" "example" "export")`. Thus, running `(add-to-list 'org-protecting-blocks "ai")` seems to fix the highlighting.

**Comment by rksm** [comment]
Should be fixed in 0.2.2.

**Comment by rksm** [comment]
https://www.youtube.com/watch?v=8SkdfdXWYaI (°o°)

Wow, I remember watching this back then in awe and actually thinking about it frequently, and also just today. You, sir, are an inspiration! I had various discussions with colleagues over the years about wether it is possible to design programming tools with voice interfaces. It looks like we are finally getting somewhere!

**Comment by tavisrudd** [comment]
Hah, thanks for the kind words! What's possible now is orders of magnitude better than what I was able to hack together back in the day. I've been using org-ai over the past few days to restructure a bunch of prose text blocks into perfectly formatted org-tables and complete with `TBLFM` column sum formulas for me. 🤯 

For anyone else finding this issue later, after upgrading `org-ai` to apply syntax highlighted to your `#+begin_ai ...` blocks just add a language major-mode name after _ai. E.g. `#+begin_ai markdown ...`. If you're using `markdown` as I am in the screenshots below, also `(setq markdown-fontify-code-blocks-natively t)`.

![Screenshot 2023-04-03 at 1 43 39 PM](https://user-images.githubusercontent.com/236886/229623905-05b96c81-ae45-4733-acfc-190e97f2d114.png)

![Screenshot 2023-04-03 at 1 43 59 PM](https://user-images.githubusercontent.com/236886/229623918-f04e8e01-6ef3-465f-a9f9-f3fc570dfb9e.png)

**Comment by tavisrudd** [comment]
@rksm would you be open to a PR which adds a newline prefix for any [AI] response that starts with a markdown code block?  The markdown mode syntax highlighting is messed up without it.

```diff
diff -u org-ai-openai.el{,.bak}
--- org-ai-openai.el    2023-04-03 13:50:21
+++ org-ai-openai.el.patched        2023-04-03 13:49:47
@@ -223,6 +223,8 @@
                    ((plist-get delta 'content)
                     (let ((text (plist-get delta 'content)))
                       (when (or org-ai--chat-got-first-response (not (string= (string-trim text) "")))
+                        (when (and (not org-ai--chat-got-first-response) (string-prefix-p "```" text))
+                            (insert "\n"))
                         (insert (decode-coding-string text 'utf-8))
                         (run-hook-with-args 'org-ai-after-chat-insertion-hook 'text text))
                       (setq org-ai--chat-got-first-response t)))
```
unpatched: ![Screenshot 2023-04-03 at 1 53 42 PM](https://user-images.githubusercontent.com/236886/229625300-106e7455-e5c2-4d4a-bef8-d11084ca6c32.png)

patched: 
![Screenshot 2023-04-03 at 1 53 58 PM](https://user-images.githubusercontent.com/236886/229625353-a829f5dc-b5f0-488e-8113-5a8f5445965e.png)

**Comment by rksm** [comment]
> For anyone else finding this issue later, after upgrading org-ai to apply syntax highlighted to your #+begin_ai ... blocks just add a language major-mode name after _ai. E.g. #+begin_ai markdown .... If you're using markdown as I am in the screenshots below, also (setq markdown-fontify-code-blocks-natively t).

That's a neat trick, I'll add this to the documentation, thanks!

> would you be open to a PR which adds a newline prefix

Absolutely, thank you!
