### ISSUE TITLE
Error on checkbox update after org-ai loaded

### ISSUE THREAD

**Issue by zondo** [rksm/org-ai#23]
**Problem**: after `org-ai` is installed, typing `C-c C-c` to toggle a checkbox when the heading has a checkbox breadcrumb (e.g., `[1/2]`) anywhere raises an error: `Lisp nesting exceeds ‘max-lisp-eval-depth’`.

Investigation shows that this is because the recursive `org-ai-special-block` function is never exiting. Which in turn is because `org-element-property` for a checkbox breadcrumb element's **:parent** is returning itself. I don't know whether that's the expected behaviour; it does seem a bit weird.

Anyhow, here's one possible workaround (checking for an infinite parent loop) that I'm using at the moment:

```emacs-lisp
(defun org-ai-special-block (&optional el)
  "Are we inside a #+begin_ai...#+end_ai block? `EL' is the current special block."
  (let (org-element-use-cache) ;; with cache enabled we get weird Cached element is incorrect warnings
    (let ((context (org-element-context el)))
      (if (equal 'special-block (org-element-type context))
          context
        (when-let ((parent (org-element-property :parent context)))
          ;; Check for parent self-reference (e.g., checkbox breadcrumb element).
          (if (equal el parent)
              nil
            (org-ai-special-block parent)))))))
```

**Comment by rksm** [comment]
Thanks for reporting!
