### ISSUE TITLE
org-ai--payload function missing encoding via utf-8

### ISSUE THREAD

**Issue by wowhxj** [rksm/org-ai#24]
Hi rksm,

Thanks for the outstanding package. I noticed that latest version missed `encode-coding-string` to utf-8 when generating payload in `org-ai--payload` function, which will cause "multibyte" error when the prompt is Chinese or other non-English language using `org-ai-prompt` function.

I add an advice to override the original `org-ai--payload` function as following in my config, it works fine. Could you please help to fix this issue?

```emacs-lisp
(cl-defun my/org-ai--payload (&optional &key prompt messages model max-tokens temperature top-p frequency-penalty presence-penalty)
  "Create the payload for the OpenAI API.
`PROMPT' is the query for completions `MESSAGES' is the query for
chatgpt. `MODEL' is the model to use. `MAX-TOKENS' is the
maximum number of tokens to generate. `TEMPERATURE' is the
temperature of the distribution. `TOP-P' is the top-p value.
`FREQUENCY-PENALTY' is the frequency penalty. `PRESENCE-PENALTY'
is the presence penalty."
  (let* ((input (if messages `(messages . ,messages) `(prompt . ,prompt)))
         ;; TODO yet unsupported properties: n, stop, logit_bias, user
         (data (map-filter (lambda (x _) x)
                           `(,input
                             (model . ,model)
                             (stream . t)
                             ,@(when max-tokens        `((max_tokens . ,max-tokens)))
                             ,@(when temperature       `((temperature . ,temperature)))
                             ,@(when top-p             `((top_p . ,top-p)))
                             ,@(when frequency-penalty `((frequency_penalty . ,frequency-penalty)))
                             ,@(when presence-penalty  `((presence_penalty . ,presence-penalty)))))))
    (encode-coding-string (json-encode data) 'utf-8)))
(advice-add 'org-ai--payload :override 'my/org-ai--payload)
```

**Comment by rksm** [comment]
Hi there, thanks for the feedback. I think there is something I really don't understand about how Emacs treats encodings.

We had previously `encode-coding-string` around the JSON data as you suggest here, however, when I try to send

```
#+begin_ai
苹果比钢球谁更重
#+end_ai
```

I'm seeing

```
Debugger entered--Lisp error: (error "Multibyte text in HTTP request: POST /v1/chat/comp...")
  error("Multibyte text in HTTP request: %s" "POST /v1/chat/completions HTTP/1.1\15\nMIME-Version: ...")
  url-http-create-request()
  url-http(#s(url :type "https" :user nil :password nil :host "api.openai.com" :portspec nil :filename "/v1/chat/completions" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous nil) #f(compiled-function (&rest args) #<bytecode 0xcd6c2bae1ccfcef>) (nil) nil tls)
  url-https(#s(url :type "https" :user nil :password nil :host "api.openai.com" :portspec nil :filename "/v1/chat/completions" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous nil) #f(compiled-function (&rest args) #<bytecode 0xcd6c2bae1ccfcef>) (nil))
  url-retrieve-internal("https://api.openai.com/v1/chat/completions" #f(compiled-function (&rest args) #<bytecode 0xcd6c2bae1ccfcef>) (nil) nil nil)
  url-retrieve("https://api.openai.com/v1/chat/completions" #f(compiled-function (&rest args) #<bytecode 0xcd6c2bae1ccfcef>) nil nil nil)
```

Digging into this thread https://lists.gnu.org/archive/html/emacs-devel/2016-11/msg00653.html, the suggested fix is similar to what we had already in place, I'm still getting the multi-byte error though. Even doing`(string-to-unibyte (encode-coding-string (json-encode data) 'utf-8))` doesn't change that. Anyway, I think this is something the url.el does that is strange.

Following up on https://github.com/rksm/org-ai/issues/3 I made this change here: https://github.com/rksm/org-ai/commit/70223e5017e1cd93b618f174fc7ce7c96b946c77 but this actually only covered up the issue as the content got double encoded.

So I'm removing the encode calls in `org-ai-complete-block` and will add `(encode-coding-string (json-encode data) 'utf-8))` as you suggest here. Please check if you get the multibyte error as I do or not. If you do not maybe your emacs version or url.el version treats that differently.

I think I'll be looking into using request.el eventually to avoid all this.

**Comment by rksm** [comment]
ooofff OK, the problem was on my side and had to do with my token NOT the content 🤦‍♂️. the token was read as a non-utf-8 string. If I also encoding that, all is good.
