### ISSUE TITLE
org-ai-on-region: Buffer is read-only: #<buffer *org-ai-on-region*>

### ISSUE THREAD

**Issue by LemonBreezes** [rksm/org-ai#25]
So when I use `org-ai-on-region` and ask for a text explanation, it creates the `*org-ai-on-region*` buffer. But if I try to do that a second time, it says `org-ai-on-region: Buffer is read-only: #<buffer *org-ai-on-region*>`. Is that happening to you too? Any workarounds? Not sure what the best solution would be.

**Comment by rksm** [comment]
Yes, thank you for noticing! Fixed now.
