### ISSUE TITLE
chinese support

### ISSUE THREAD

**Issue by alan-w-255** [rksm/org-ai#3]
During usage, it is unable to recognize Chinese input and output Chinese characters in garbled format. For instance, using a prompt "teach me a Chinese word" may output messy codes.

**Comment by gfgkmn** [comment]
It seems that the issue with handling Chinese input still persists. I have tried two examples.

first: 
#+begin_ai :max-tokens 250
[SYS]: You are a helpful assistant. you could understand chinese
[ME]: how to say apple in chinese
[AI]: 苹果 (píng guǒ) is how you would say "apple" in Chinese.
[ME]: 
#+end_ai

That's fine. However, if I directly input Chinese characters like this:
#+begin_ai :max-tokens 250
[SYS]: You are a helpful assistant. you could understand chinese
[ME]: how to say apple in chinese
[AI]: 苹果 (píng guǒ) is how you would say "apple" in Chinese.
[ME]: 苹果比钢球谁更重
#+end_ai

A multibyte error occurs:

`error in process sentinel: Multibyte text in HTTP request: POST /v1/chat/completions HTTP/1.1
MIME-Version: 1.0
Connection: keep-alive
Extension: Security/Digest Security/SSL
Host: api.openai.com
Accept-encoding: gzip
Accept: */*
User-Agent: URL/Emacs Emacs/28.2 (nil; aarch64-apple-darwin21.6.0)
Authorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: application/json
Content-length: 362

{"messages":[{"role":"system","content":"You are a helpful assistant. you could understand chinese"},{"role":"user","content":"how to say apple in chinese"},{"role":"assistant","content":"苹果 (píng guǒ) is how you would say \"apple\" in Chinese."},{"role":"user","content":"苹果比钢球谁更重"}],"model":"gpt-3.5-turbo","stream":true,"max_tokens":250}
Auto-saving...done
Quit [2 times]
`
![CleanShot_2023-03-19_at_13 03 21@2x](https://user-images.githubusercontent.com/4817005/226154832-0cdac5d7-ff1a-4e2f-ad66-db83156251f5.png)


I have tried multiple times, even with GPT-4's assistant, but I still couldn't figure it out.

Couldn't you give some clue to solve it?

**Comment by alan-w-255** [comment]
it works on emacs master branch， which is emacs 30. i think it caused by the different versiond of url library

**Comment by alan-w-255** [comment]
I never see those ^M characters. Maybe it will fixed by get rid of those ^M characters.

**Comment by gfgkmn** [comment]
@alan-w-255 It's possible that the issue is related to Emacs 28.2 and Doom. I've noticed that there have been similar problems reported in the past, as seen in the following links:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23750
https://github.com/magit/ghub/issues/12
https://github.com/karthink/gptel/issues/4
However, I'm still unsure about how to resolve this issue in the current version.

**Comment by nasyxx** [comment]
> i think it caused by the different versions of the url library

How to confirm the version of url lib? I just compiled emacs30 from master and still encounter this problem.

**Comment by olavfosse** [comment]
I think this occurs with all non-ASCII characters. I get it whenever I enter æøå and also sometimes seemingly at random some times.

**Comment by olavfosse** [comment]
I'll try updating

```
ELISP> (version)
"GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.3.0, Carbon Version 169 AppKit 2299.4)
 of 2023-03-01"
```

**Comment by rksm** [comment]
I think this change here should address the problem: https://github.com/rksm/org-ai/commit/70223e5017e1cd93b618f174fc7ce7c96b946c77

Please feel free to open this issue if not.

**Comment by rksm** [comment]
ooofff OK, the problem was on my side and had to do with my token NOT the content 🤦‍♂️. the token was read as a non-utf-8 string. If I also encoding that, all is good.

**Comment by olavfosse** [comment]
> I think this change here should address the problem: [70223e5](https://github.com/rksm/org-ai/commit/70223e5017e1cd93b618f174fc7ce7c96b946c77)
> 
> Please feel free to open this issue if not.

It works now. Thanks!
