### ISSUE TITLE
angle brackets being added to the beginning of responses

### ISSUE THREAD

**Issue by LemonBreezes** [rksm/org-ai#30]
Hi. Very often, when I am using `org-ai-refactor-code`, I am being given a response that contains `< ` at the beginning of every line like if it were a quoted comment on GitHub. How do I stop this? Is this happening to anyone else?
![image](https://user-images.githubusercontent.com/29102529/232232559-26c4d1e5-5e78-44a8-8975-9d83fd22e806.png)

**Comment by rksm** [comment]
Thank you for the report.

I've not seen this yet, I'll try to reproduce. What model are you using? gpt-3 or 4?

**Comment by LemonBreezes** [comment]
GPT4. I think it has to do with the prompt or something. Dunno.

**Comment by rksm** [comment]
I modified the default prompt so that this shouldn't happen anymore.
