### ISSUE TITLE
Consecutive calls to `org-ai-kill-region-at-point append output in reverse

### ISSUE THREAD

**Issue by LemonBreezes** [rksm/org-ai#32]
![image](https://user-images.githubusercontent.com/29102529/232365516-799113c6-36aa-4e9d-9b34-cccf0282f6b0.png)
If I call `org-ai-kill-region-at-point` and then paste
![image](https://user-images.githubusercontent.com/29102529/232365625-56dd21fb-ba7d-4c7a-a335-56979dad4273.png)
I get this. So the consecutive kills are appended to one another rather than prepended.

**Comment by rksm** [comment]
Thanks! Fixed now.
