### ISSUE TITLE
stuck on Contacting host: api.openai.com:443 

### ISSUE THREAD

**Issue by soheilred** [rksm/org-ai#43]
I used to use org-ai for a while, and it has been working flawlessly. Since yesterday, when I try to execute an ai block I get the following message in my messages buffer:

`Contacting host: api.openai.com:443 `

I refreshed my api keys, but nothing changed.
Any idea what is going on?

**Comment by soheilred** [comment]
It seems to be quota problem. I get an `insufficient_quota` error with the following message:
You exceeded your current quota, please check your plan and billing details.
This is weird! According to their [rate limits](https://platform.openai.com/docs/guides/rate-limits/overview) documentation, free users should be able to use GPT-4 for free, as far as they don't exceed 3 Request Per Minutes (RPM).

**Comment by rksm** [comment]
OK, just in case,do you have the raw results from the `url-retrieve-synchronously` requests around above? I can't help with the cause of the issue but I can try to make the error message better.

**Comment by mberndtgen** [comment]
May I jump in (I'm experiencing the same issue): evaluating the expression from above gives this output:

```
HTTP/1.1 429 Too Many Requests
Date: Sat, 06 May 2023 22:39:46 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 206
Connection: keep-alive
vary: Origin
x-request-id: 976373fcd5c5f57c8824dd133abf4efd
strict-transport-security: max-age=15724800; includeSubDomains
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 7c34b89b0f81373c-FRA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

Same with that curl command. That HTTP 429 is strange.

**Comment by rksm** [comment]
org-ai should now open a buffer explaining the error. Please reopen if that doesn't work.
