### ISSUE TITLE
write API response in a separate block?

### ISSUE THREAD

**Issue by titaniumbones** [rksm/org-ai#44]
I often want to rerun a previous request. Would you be amenable to an option that moves the response to its own block?

**Comment by rksm** [comment]
Sure, what works right now is to use `org-ai-kill-region-at-point` (bound to `C-c <backspace>` by default), which will delete the chat region under point and add it to the kill-ring. So what I typically do is, when a response is done, hit `C-c <backspace>` twice (one for the empty `[ME]:`, once for the response and I'm back at the original prompt.

Is this sufficient?
