### ISSUE TITLE
`C-c C-c` not working for `+begin_ai` ... `+end_ai`

### ISSUE THREAD

**Issue by mgudemann** [rksm/org-ai#52]
Thanks a lot for this package.

It works fine using `org-ai-complete-block`, but `C-c C-c` only returns `... can do nothing useful here` when inside a `+begin_ai ... +end_ai` Block

Emacs is `28.2` and I have
```
ELISP> org-protecting-blocks
("ai" "src" "example" "export")
```
so the setup of `org-ai-block` apparently worked.

Any hint what might be missing from my config?

**Comment by rksm** [comment]
Do you have a minimal / small example of an org text that doesn't work? Thanks!

**Comment by tabfugnic** [comment]
I'm seeing the same issue.

My text is simply:

```org
#+begin_ai
  What is the best text editor?
#+end_ai
```

When I run `C-c C-c` is get 

```
C-c C-c can do nothing useful here
```

**Comment by tabfugnic** [comment]
Fixed my issue. I must have missed the install section that involved adding the hook to my config. It now works as expected.

**Comment by mgudemann** [comment]
thanks for pointing this out. Solved the issue for me too.
