### ISSUE TITLE
Defer using auth-source to get the API key

### ISSUE THREAD

**Issue by rjekker** [rksm/org-ai#55]
I need to enter a password to unlock the GPG agent for my auth source; and I need to physically insert a key as well.

You do a call to auth-source when org-ai-openai.el gets loaded; this makes loading org-ai at startup a problem since now emacs will wait for me to allow it to open the auth file; I'd rather not have to do that.

Apart from that, you are loading the secret into memory and keeping it in the variable for my entire emacs session - which can take days.

For those reasons it would be better to load the secret from the auth file only when you actually do a request and then immediately forget it again. This way we can make use of the gpg-agent session that locks after a while.

I suggest something along the lines of: (I didn't test this, hope you get the idea)

```elisp
(defun get-api-key ()
  (or org-ai-openai-api-token
      (when org-ai-use-auth-source 
        (require 'auth-source)
        (auth-source-pick-first-password :host "api.openai.com" :user "org-ai"))))
```

You would then call this function before every request, and bind it to a local variable with "let", instead of just using the org-ai-openai-api-token variable.

**Comment by rksm** [comment]
This is the code that is part of org-ai already:

```elisp
(defcustom org-ai-use-auth-source t
  "If non-nil, use auth-source to retrieve the OpenAI API token.
The secret should be stored in the format
  machine api.openai.com login org-ai password <your token>
in the `auth-sources' file."
  :type 'boolean
  :group 'org-ai)

(when (and org-ai-use-auth-source (not org-ai-openai-api-token))
  (require 'auth-source)
  (when-let ((secret (auth-source-pick-first-password :host "api.openai.com" :user "org-ai")))
    (setq org-ai-openai-api-token secret)))
```

So simply setting `(setq org-ai-use-auth-source nil)` should do the trick. Feel free to reopen if you run into trouble.

**Comment by rjekker** [comment]
The problematic code is your "when" statement. There are two problems here:

1. This runs when the library is loaded. When using auth-source, this will cause emacs to wait for unlocking of the auth store. That means a password might need to be entered, a security key to be inserted, etc. When you run emacs as a daemon you may not see the prompt - emacs will not start.

2. You store the secret in a global variable. That is a bad practice from a security standpoint. It's better to get the key from the authstore for every request and not store it at all. That way, when the GPG agent's session ends, you will be prompted for the password again.
