### ISSUE TITLE
org-ai-global-mode not working 

### ISSUE THREAD

**Issue by geoffwalmsley** [rksm/org-ai#59]
I have added org-ai-global-mode in my setup as per the docs:
```
(use-package org-ai
  :ensure t
  :commands (org-ai-mode
	     org-ai-global-mode)
  :custom
  (org-ai-openai-api-token (my-auth 'gpt))
  :init
  (add-hook 'org-mode-hook #'org-ai-mode)
  (org-ai-global-mode)
  :config
  (setq org-ai-default-chat-model "gpt-4")
  (setq markdown-fontify-code-blocks-natively t)
 )
```

After reloading/restarting the `C-c M-a` command doesn't work. If I manually `M-x org-ai-global-mode` it will work in the current active buffer but that's all. I thought this would set the mode globally but doesn't seem to behave as expected.

Possibly this line: https://github.com/rksm/org-ai/blob/b10f20b8e9fd00e7cfad3a5ebe0e5756de666354/org-ai.el#L217C1-L218C1

should be 
```
(global-set-key (kbd "C-c M-a") org-ai-global-prefix-map)
```

**Comment by rksm** [comment]
Hmm that's strange. Do you have another package installed that might capture that keybinding (try `C-h k C-c M-a`)?

I'm testing a from-scratch setup as follows:

This init file is saved as `only-org-ai.el`:

```elisp
(require 'package)
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-user-dir (expand-file-name "elpa-only-org-ai/" user-emacs-directory))
(package-initialize)

(use-package org-ai
  :ensure t
  :commands (org-ai-mode
	     org-ai-global-mode)
  :init
  (add-hook 'org-mode-hook #'org-ai-mode)
  (org-ai-global-mode)
  :config
  (setq org-ai-default-chat-model "gpt-4")
  (setq markdown-fontify-code-blocks-natively t))
```

 I then run `emacs --no-init-file --no-splash --load ./only-org-ai.el`. In that case, e.g. `C-c M-a P` resolves correctly to `org-ai-prompt`. Can you test the same and see if the command is bound? If yes, something might be interfering.

**Comment by geoffwalmsley** [comment]
Thanks for the reply. Most likely there is a conflict with org-capture
so I've just brute-forced my setup to make everything work. I also forked
your repo and added a way of using org-ai similar to how I use org-capture.
So in addition to a "notes.org", "journal.org" etc, I have "gpt.org". I
then bound "C-c M-a n" to open my gpt file, go to the bottom, insert a new
ai block and put point in the right place so I can immediately start typing
and yanking code snippets. It's probably a bit different to the way you
envision people using it, but works really well for me. Thanks for putting
together the pieces to allow me to set up this workflow, you're a legend:)

**Comment by rksm** [comment]
Thank you & whatever works best, that's why Emacs is so cool :)
