### ISSUE TITLE
Interested in joining forces?

### ISSUE THREAD

**Issue by freckletonj** [rksm/org-ai#74]
Hi, I'm the author of [UniteAI](https://github.com/freckletonj/uniteai), and I like what you're working on. My project is similar but doesn't have image support yet. Also, I love your interface you went with. 

The major difference is, I'm using a python backend so that any editor can use it (via LSP), and so that its easy to add any model (such as speech-to-text, image gen, document embeddings, etc.)

I'd be curious for your feedback on UniteAI, and I'd love to join forces. We could start a discord or something and coordinate. If you're interested :)

**Comment by rksm** [comment]
Hi there! Thank you for the offer but at this point I need to decline.

On the one hand, I would like to keep org-ai free from non-emacs dependencies as much as possible to ease setup.

Also, I'm currently deep in another project and don't have the necessary bandwidth at this point.

In any case, good luck!
