### ISSUE TITLE
How to have lengthy interaction that exceeds 4096 tokens?

### ISSUE THREAD

**Issue by tillydray** [rksm/org-ai#75]
I may be using org-ai incorrectly. I'm trying to have a lengthy interaction that requires me to provide chatGPT with a lot of context. Several pages worth. How can I do this and have an arbitrarily-long interaction without hitting this 4096 token limit? Do I need to use multiple `ai` blocks? I tried and chatGPT no longer had the context so I'm not sure how to do this.

**Comment by rksm** [comment]
So by default, org-ai does not try to do anything about the token limit. You can use different models that open ai provides (and that can be switched to either with the `:model` keyword in an org-ai block or by setting `org-ai-default-chat-model`). The actual model names can be found here: https://platform.openai.com/docs/models/overview.

At this time you can switch to `gpt-4` which as 8192 tokens or `gpt-3.5-turbo-16k` for 16k tokens. There is `gpt-4-32k` but I think you need to be explicitly whitelisted for this.

Other than that, you could create your own solution with a bit of scripting, based on your input. E.g. I've might a pretty usable summarizer by splitting up the input text into n chunks, asking for summaries of those and then eventually taking the combined output as input to a last prompt and asking for a summary of that. Basically map and reduce.

But at this point there is no support in org-ai built-in, so you would need elisp code to call e.g. `org-ai-prompt` programatically. The Python SDK might be the easier platform in this case. I also don't plan to add anything like this to org-ai as the specific solutions need to be adapted to the actual problem.
