### ISSUE TITLE
Bug in org-ai-global-mode

### ISSUE THREAD

**Issue by orgmodes** [rksm/org-ai#76]
Following the discussion in #59 , I tried and failed to get `org-ai-global-mode` working. I ended up posting on Emacs Stack Exchange ([here](https://emacs.stackexchange.com/questions/78490/difference-between-emacs-and-emacs-load-init-el/78494?noredirect=1#comment131270_78494)), and got the following answer:

> The package has a bug. The mode isn't actually global, so when you enable it you do so buffer-locally (and even that quickly gets squashed by the major mode for the initial buffer being called, clobbering all buffer-local variables).
>
> org-ai-global-mode is a variable defined in ‘org-ai.el’.
>
> Its value is nil
>
> Non-nil if Org-Ai-Global mode is enabled.
> Use the command ‘org-ai-global-mode’ to change this variable.
>
>  Automatically becomes buffer-local when set.

> Note that final "buffer-local" statement, which we would never expect to see for a purportedly "global" minor mode.

```
(define-minor-mode org-ai-global-mode
  "Non `org-mode' specific minor mode for the OpenAI API."
        :init-value nil
        :lighter ""
        :diminish <==== this line is a bug
        :global t
        :keymap org-ai-global-mode-map
        :group 'org-ai)
```
> I believe the author of this code used a keyword designed for use-package by accident. It's certainly not a valid keyword argument for define-minor-mode, and there's no value attached to it, so it messes up all of the remaining keyword behaviours, which are required (in this macro) to come in pairs.

> I.e. this says `:diminish :global` as a pair, and the remainder (starting from non-keyword t) all get evaluated (harmlessly) as the mode's body:
```
t
:keymap
org-ai-global-mode-map
:group
'org-ai
```
> org-ai-global-mode-map is defined by that point, and the rest are just symbols, so no error occurs from evaluating that sequence.

Do you think you could take a look? I can try to make a PR but I'm very new to Emacs and orgmode and I'm not sure I will find the right way to do it myself.

Thanks!

**Comment by rksm** [comment]
Hi, yeah that was a mistake, sorry. Should be fixed now. Thanks for pointing this out!
