### ISSUE TITLE
Code Llama support?

### ISSUE THREAD

**Issue by jbsolomon** [rksm/org-ai#78]
Hi, I was just wondering a) if you could estimate the level of effort to integrate self-hosted Code Llama, and b) where I (or someone) could start with a PR for this, if c) you are not already planning to implement it.

**Comment by ententent** [comment]
Supporting interface with local large language model is awesome

**Comment by LemonBreezes** [comment]
Yeah, if we get Llama support, that will be really awesome.

**Comment by rksm** [comment]
Alrighty, I'll add an integration with https://github.com/oobabooga/text-generation-webui/.

**Comment by yhslai** [comment]
What kind of template does it send to the local LLM tho? Just strip out [ME] and [AI] and send the full conversation?

**Comment by rksm** [comment]
So there are two ways to customize that:

You can change the "role" placeholders by customizing [`org-ai-oobabooga-system-prefix`, `org-ai-oobabooga-user-prefix`, `org-ai-oobabooga-assistant-prefix`](https://github.com/rksm/org-ai/blob/master/org-ai-oobabooga.el#L42]. The prompt text will then be those placeholders concatenated with the text in the org ai block.

If you want more control, you can customize [`org-ai-oobabooga-create-prompt-function`](https://github.com/rksm/org-ai/blob/master/org-ai-oobabooga.el#L110). It defaults to `org-ai-oobabooga-create-prompt-default` which does the behavior mentioned above but you can add any arbitrary logic. E.g.

```elisp
(setq org-ai-oobabooga-create-prompt-function
      (lambda (messages)
        (cl-loop for msg across messages
                 for role = (plist-get msg :role)
                 for content = (plist-get msg :content)
                 collect (cond ((eql role 'system) (format "SYSTEM %s" content))
                               ((eql role 'user) (format "USER %s" content))
                               ((eql role 'assistant) (format "ASSISTANT %s" content)))
                 into result
                 finally return (string-join result "\n\n"))))
```
