### ISSUE TITLE
model paamater  not passing

### ISSUE THREAD

**Issue by bradydonald** [rksm/org-ai#8]
Added this to my config but when I make requests this is the response I get:

HTTP/1.1 400 Bad Request
Date: Thu, 16 Mar 2023 04:11:44 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 167
Connection: keep-alive
Vary: Origin
X-Request-Id: b5a15e6f2c0393541ebf534626fd269c
Strict-Transport-Security: max-age=15724800; includeSubDomains

{
    "error": {
        "message": "you must provide a model parameter",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

I'm using Tag:      v0.1.3 (1)

here is my config code. I have verified api-key code:

* Chat GPT Integration (Experimental)

  Using https://github.com/rksm/org-ai
  
  #+BEGIN_SRC emacs-lisp

    (setq db/org-ai t)

    (if (and (file-directory-p "~/.emacs.d/lisp/org-ai") db/org-ai)
        (use-package org-ai
          :load-path (lambda () "lisp/org-ai")
          :commands (org-ai-mode)
          :custom
          (org-ai-openai-api-token (shell-command-to-string "gpg -q -d ~/.openai-api.key.gpg"))
          :init
          (add-hook 'org-mode-hook #'org-ai-mode)
          :config
          (advice-add 'keyboard-quit :before #'org-ai-keyboard-quit)))

  #+END_SRC

**Comment by rksm** [comment]
Did you make the request from an `#+begin_ai...#+end_ai` block. How did the block look like, in particular the header?

**Comment by bradydonald** [comment]
Yes, I did. Here is the exact block I am testing:

#+BEGIN_AI
  what is the meaning of life?
#+END_AI

**Comment by bradydonald** [comment]
I noticed you asked about the header. The bock above I just added to the end of my .emacs literate config so here is it in context with the header:

* Start a server

  #+BEGIN_SRC emacs-lisp
    (load "server")
    (unless (server-running-p) (server-start))
  #+END_SRC

#+BEGIN_AI
  what is the meaning of life?
#+END_AI

and I am executing it with C-c C-c in my testing.

**Comment by rksm** [comment]
OK, let's try to figure out where things go wrong. Just to check, you are on the latest version, correct?

Can you put the following [between line 353 and 354](https://github.com/rksm/org-ai/blob/master/org-ai.el#L354):

```elisp
(message "org-ai-stream-request %s" (list prompt messages callback model max-tokens temperature top-p frequency-penalty presence-penalty))
```

and run `M-x eval-defun` on that function.

When you then evaluate a block, your message buffer (`C-h e`) should display something like

```
org-ai-stream-request (nil [(:role user :content what is the meaning of life?)] (closure ((buffer . *scratch* (org-ai)) (context special-block (:type AI :parameters nil :begin 179 :end 230 :contents-begin 190 :contents-end 219 :post-blank 2 :post-affiliated 179 :mode nil :granularity element :parent (section (:begin 1 :end 251 :contents-begin 1 :contents-end 251 :robust-begin 1 :robust-end 249 :post-blank 0 :post-affiliated 1 :mode first-section :granularity element :parent (org-data (:begin 1 :contents-begin 1 :contents-end 251 :end 251 :robust-begin 3 :robust-end 249 :post-blank 0 :post-affiliated 1 :path nil :mode org-data :CATEGORY nil))))))) (result) (org-ai--insert-chat-completion-response context buffer result)) gpt-3.5-turbo nil nil nil nil nil)
```

Is this the case? If it is not (in particular if it does not contain `gpt-3.5-turbo`), can you check what the value of `org-ai-default-chat-model` is?

Thanks!

**Comment by bradydonald** [comment]
Hi, following your instructions here is the output:

org-ai-stream-request (nil [(:role user :content what is the meaning of life?)] (closure ((buffer . configuration.org) (context special-block (:type AI :parameters nil :begin 47940 :end 47998 :contents-begin 47953 :contents-end 47984 :post-blank 1 :post-affiliated 47940 :mode nil :granularity element :parent (section (:begin 47835 :end 47998 :contents-begin 47835 :contents-end 47995 :robust-begin 47835 :robust-end 47993 :post-blank 1 :post-affiliated 47835 :mode section :granularity element :parent (headline (:raw-value Start a server :begin 47817 :end 47998 :pre-blank 1 :contents-begin 47835 :contents-end 47995 :robust-begin 47837 :robust-end 47993 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 1 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 47817 :title Start a server))))))) (result) (org-ai--insert-chat-completion-response context buffer result)) gpt-3.5-turbo 120 nil nil nil nil)
Contacting host: api.openai.com:443


Also..

org-ai-default-chat-model is a variable defined in ‘org-ai.el’.

Its value is "gpt-3.5-turbo"

The default model to use for chat-gpt requests. See https://platform.openai.com/docs/models for other options.

  You can customize this variable.

**Comment by bradydonald** [comment]
Also, if it makes a difference I have a paid sub and an on GPT-4 beta.

**Comment by rksm** [comment]
The request looks fine, maybe it is because gpt-4. Can you try setting `(setq org-ai-default-chat-model "gpt-4")`? And you are on the latest version, right?

**Comment by bradydonald** [comment]
Yes. Just updated this morning. Magit log:

8748ac5 * master origin/master v0.1.4 Support for retrieving `org-ai-openai-api-token` from `authinfo` file.

I added the two debugging steps back in again and set mode to gpt-4. Here's the outputs again:

buffer poped:

HTTP/1.1 400 Bad Request
Date: Sun, 19 Mar 2023 07:49:08 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 167
Connection: keep-alive
Vary: Origin
X-Request-Id: ab38d191348dbb8b5b2b63aa34e8ad65
Strict-Transport-Security: max-age=15724800; includeSubDomains

{
    "error": {
        "message": "you must provide a model parameter",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

Messages:

org-ai-stream-request (nil [(:role user :content what is the meaning of life?)] (closure ((buffer . configuration.org) (context special-block (:type AI :parameters nil :begin 47940 :end 47998 :contents-begin 47953 :contents-end 47984 :post-blank 1 :post-affiliated 47940 :mode nil :granularity element :parent (section (:begin 47835 :end 47998 :contents-begin 47835 :contents-end 47995 :robust-begin 47835 :robust-end 47993 :post-blank 1 :post-affiliated 47835 :mode section :granularity element :parent (headline (:raw-value Start a server :begin 47817 :end 47998 :pre-blank 1 :contents-begin 47835 :contents-end 47995 :robust-begin 47837 :robust-end 47993 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 1 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 47817 :title Start a server))))))) (result) (org-ai--insert-chat-completion-response context buffer result)) gpt-4 120 nil nil nil nil)
Contacting host: api.openai.com:443


Not sure what's going on.

**Comment by rksm** [comment]
Can you please try to emacs-lisp eval the following (e.g. `M-x eval-expression` and paste that into your minibuffer):

```elisp

(let ((url-request-extra-headers `(("Authorization" . ,(string-join `("Bearer" ,org-ai-openai-api-token) " "))
                                   ("Content-Type" . "application/json")))
      (url-request-method "POST")
      (url-request-data (encode-coding-string
                         (org-ai--payload :messages [(:role "user" :content "what is the meaning of life?")]
					  :model "gpt-4")
                         'utf-8)))
  (pop-to-buffer (url-retrieve "https://api.openai.com/v1/chat/completions" (lambda () (print "done")))))
```

This is the minimum that's needed to work to communicate with the API. It should open an http buffer that has a number of `data: ...` lines in it. Please let me know if this works or what instead happens. Thank you!

**Comment by bradydonald** [comment]
Seems that does not happen. I get this following:

#<buffer  *http api.openai.com:443*-459085>HTTP/1.1 400 Bad Request
Date: Mon, 20 Mar 2023 18:09:01 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 167
Connection: keep-alive
Vary: Origin
X-Request-Id: 11c8809e2aac17fc9712dbf64ec5460b
Strict-Transport-Security: max-age=15724800; includeSubDomains

{
    "error": {
        "message": "you must provide a model parameter",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by rksm** [comment]
OK, thanks for checking!

**Comment by bradydonald** [comment]
Figured it out. There was a trailing newline in the api key so this works:

* Chat GPT Integration

  Using https://github.com/rksm/org-ai
  
  #+BEGIN_SRC emacs-lisp

    (setq db/org-ai t)

    (defun db/openai-api-key ()
      (substring (shell-command-to-string "gpg -q -d ~/.openai-api.key.gpg") 0 -1))
    
    (if (and (file-directory-p "~/.emacs.d/lisp/org-ai") db/org-ai)
        (use-package org-ai
          :load-path (lambda () "lisp/org-ai")
          :commands (org-ai-mode)
          :custom
          (org-ai-openai-api-token (db/openai-api-key))
          :init
          (add-hook 'org-mode-hook #'org-ai-mode)
          :config
          (advice-add 'keyboard-quit :before #'org-ai-keyboard-quit)))

  #+END_SRC

**Comment by rksm** [comment]
Cool, note that you can also use auth-sources: https://github.com/rksm/org-ai#api-key-with-auth-source
