### ISSUE TITLE
Integrate Mistral 7B?

### ISSUE THREAD

**Issue by lullis** [rksm/org-ai#84]
Fully open source and claiming to beat llama on some benchmarks. How could one go around setting this up?

**Comment by LemonBreezes** [comment]
When using local AI, I set up https://github.com/oobabooga/text-generation-webui and once the oobabooga web UI was up and running, `org-ai` src blocks with `:local` just worked magically. Org AI uses `org-ai-oobabooga-websocket-url` which worked for me for the `oobabooga` defaults.

**Comment by rksm** [comment]
Yep exactly, the oobabooga/text-generation-webui project is awesome and should allow you to choose mistral.
