### ISSUE TITLE
Org Ai on region

### ISSUE THREAD

**Issue by prajwaljpj** [rksm/org-ai#85]
I have installed org-ai on doom emacs
when I select a region on my code and call org-ai-on-region and ask a question. I get this error

> org-ai was not able to extract begining/end of the org-ai block

Is there something I can do to fix it?

**Comment by prajwaljpj** [comment]
On further investigation, i think the begin_ai ... end_ai blocks are not being detected

```org-mode
#+begin_ai
is emacs the best editor?
#+end_ai

#+begin_src python :results output
print("hello world")
#+end_src

#+RESULTS:
: hello world
```

here `C-c C-c` outputs `C-c C-c can do nothing useful here` on the begin-ai block

**Comment by rksm** [comment]
Hmm just pasting that into an otherwise empty org buffer didn't let me reproduce. Where is your cursor when that happens?

**Comment by prajwaljpj** [comment]
The cursor is on the `begin..end_ai` blocks. If I place the cursor on the text inside the `begin..end_ai` blocks, I get this message `cannot find the begining/end of ai blocks`. For more information, here is my configuration files
Doom emacs uses straight for package management.
package.el
```elisp
(package! org-ai
  :recipe (:host github :repo "rksm/org-ai"
           :files ("*.el" "README.md" "snippets")))
```
config.el
```elisp
(use-package! org-ai
  :ensure t
  :load-path (lambda () "~/.config/emacs/.local/straight/repos/org-ai")
  :init
  (add-hook 'org-mode-hook #'org-ai-mode)
  (org-ai-global-mode) ; installs global keybindings on C-c M-a
  :config
  (setq org-ai-openai-api-token "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
  (setq org-ai-default-chat-model "gpt-4") ; if you are on the gpt-4 beta:
  (org-ai-install-yasnippets)
  )
```
I found the culprit! it looks like we have to specify `load-path` in `config.el` to where org-ai is cloned
`:load-path (lambda () "~/.config/emacs/.local/straight/repos/org-ai")` 

Thank you for your help!
