### ISSUE TITLE
More informative error message

### ISSUE THREAD

**Issue by tynesjo** [rksm/org-ai#87]
#### Context
Backend: ChatGPT
Org-ai version: 20230910.151451

#### Issue
If the API returns an error for reasons unrelated to the model parameter, such as:
1. API token not valid for further requests
2. connection issue with curl / lower level networking

Then an error message suggesting a model parameter is missing is returned: 
 
> Error from OpenAI API:
>
> you must provide a model parameter

This slows down debugging

#### Proposed solution
- error message to reflect the reason for underlying the API request error

**Comment by tynesjo** [comment]
Closing due to said error message coming from the API and not the org-ai package.

(Problem was related to spacemacs configuration affecting both org-ai package and its openai layer).

**Comment by santiyounger** [comment]
did you manage to get org-ai to work on spacemacs, it just returns the error for me, but I tripled checked correct configuration and still returns this error

Thanks

**Comment by tynesjo** [comment]
Yes I got it to o work on spacemacs,
In case it helps: in my case the issue was related to the token having a stray newline character at the end and the 
OpenAI API returning an error message which did not reflect the token being incorrect or incorrectly formatted
