### ISSUE TITLE
Not receiving chat messages

### ISSUE THREAD

**Issue by erikc96** [rksm/org-ai#9]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/19583572/226059636-57b0e97d-e9ef-4b89-97b2-8596d190daf8.png">

<img width="356" alt="image" src="https://user-images.githubusercontent.com/19583572/226059662-3096827f-7beb-41e8-8cb9-65580fde022a.png">

Screenshots show what I'm seeing and what prompts I'm using. When I hit C-C C-c I get the notification in the corner that emacs is contacting OpenAI, but nothing else happens. When I go to the open ai website, I can see that that my access token has been used.

My config is copy pasted from the README, with my access key added.

**Comment by rksm** [comment]
Could you please uncomment line 378 in org-ai.el (https://github.com/rksm/org-ai/blob/master/org-ai.el#L378) and then do `M-x eval-defun`. Afterwards run a prompt. There should be a buffer ` *http api.openai.com:443*` popping up. Please paste the content in here. Thank you!

**Comment by erikc96** [comment]
It was my account, but thanks for sharing how to debug!
