### ISSUE TITLE
The model `gpt-4-32k` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by tillydray** [rksm/org-ai#91]
I'm getting this error but I do have access to that model. I'm not sure how I can prove that to you though. When I use `gpt-4-1106-preview` I don't get the error, instead things work as expected. I'm not sure what info you need to troubleshoot. Here are the relevant buffers, not very helpful

\*org-ai error\*
```
Error from OpenAI API:

The model `gpt-4-32k` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

\*messages\*
```
Contacting host: api.openai.com:443
```

**Comment by rksm** [comment]
org-ai is just using the OpenAI API. Can you run requests with `gpt-4-32k` in the playground https://platform.openai.com/playground?

**Comment by tillydray** [comment]
> org-ai is just using the OpenAI API. Can you run requests with `gpt-4-32k` in the playground https://platform.openai.com/playground?

`gpt-4-32k` isn't listed in the dropdown. There are a few gpt-4 versions however. https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo shows `gpt-4-32k` as a valid model but I guess that documentation is either out-of-date or not the correct source of truth for this.

**Comment by rksm** [comment]
Hmm yeah sorry, I don't think I can help with that. Maybe trying `(setq org-ai-default-chat-model "gpt-4-32k-0613")`. In any case, whatever works in API calls should work for org-ai as well.
